---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Copy WAR file to Tomcat
      copy:
        src: "../target/MavenAnsibleWebApp.war"
        dest: "/var/lib/tomcat9/webapps/MavenAnsibleWebApp.war"
        force: yes

    - name: Restart Tomcat
      systemd:
        name: tomcat9
        state: restarted
